### ISSUE TITLE
Unresolved dependencies: scala version 2.12.0 or 2.11.8

### ISSUE THREAD

**Issue by hmf** [bytedeco/sbt-javacpp#11]
Hello, 

I would like to know if the library is available for Scala versions 2.11 and 2.12.
When I "sbt eclipse" using the latest version of the library (1.8) and sbt picks 
Scala version "2.10.6", everything is ok. 

However, versions "2.12.0" and "2.11.8" don't work. I get:
```
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.bytedeco#sbt-javacpp;1.8: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		org.bytedeco:sbt-javacpp:1.8 (scalaVersion=2.12, sbtVersion=0.13)
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.bytedeco:sbt-javacpp:1.8 (scalaVersion=2.12, sbtVersion=0.13) (/tmp/test_sbt/build.sbt#L2-3)
[warn] 		  +- myproject:myproject_2.12:1.0

```
Any way I can solve this?

TIA.

**Comment by lloydmeta** [comment]
As far as I know, SBT itself, and thus its plugins are all still stuck on 2.10.

How are you adding sbt-javacpp into your project?

**Comment by hmf** [comment]
Hi Lloyd,

Ok, I was not aware that stb was on 2.10. But I assume this is not the issue.

I have the following build.sbt:

```
// Eclipse plugin
EclipseKeys.useProjectId := true
EclipseKeys.createSrc := EclipseCreateSrc.Default + EclipseCreateSrc.ManagedClasses
EclipseKeys.executionEnvironment := Some(EclipseExecutionEnvironment.JavaSE18)
EclipseKeys.withSource := true
EclipseKeys.withJavadoc := true
EclipseKeys.withBundledScalaContainers := false

name := "Test1"

version := "0.1"

scalaVersion := "2.12.0"
//scalaVersion := "2.11.8"

resolvers += "Typesafe Repository" at "http://repo.typesafe.com/typesafe/releases/"
resolvers += "Sonatype OSS Snapshots" at "http://oss.sonatype.org/content/repositories/snapshots/"

libraryDependencies += "org.bytedeco" % "javacpp" % "1.2.4"
libraryDependencies += "org.nd4j" % "nd4j-native-platform" % "0.4.0"

scalacOptions ++= Seq("-unchecked", "-deprecation")
```

and in /projects/plugins.sbt I have:

```
addSbtPlugin("org.bytedeco" % "sbt-javacpp" % "1.8")

```

If you see anything amiss, please tell.

TIA,
Hugo F.

**Comment by lloydmeta** [comment]
That all looks fine to me. On my own projects, everything resolves fine and both `sbt eclipse` and `sbt run` work fine because the artefact is downloadable.

Can you put your project up on Github for us to have a look?

**Comment by hmf** [comment]
Finally solved the issue. Added the following line:

```
resolvers += "mvnrepository" at "http://mvnrepository.com/artifact/"
```

Thanks for the help.

**Comment by lloydmeta** [comment]
That's odd, the plugin is published to Maven Central, which is one of the default resolvers.

Anyway, glad you managed to solve it.
