### ISSUE TITLE
Update Javacpp to 1.3.2

### ISSUE THREAD

**Issue by pommedeterresautee** [bytedeco/sbt-javacpp#13]
Version 1.3.1 improves scala Object support
https://github.com/bytedeco/javacpp/blob/master/CHANGELOG.md#december-24-2016-version-131

Current SBT plugin depends on version 1.2.5

Would it be possible to bump to 1.3.2 (last version in date of Javacpp) and publish it?

**Comment by lloydmeta** [comment]
Definitely; would you like to open a PR?

**Comment by pommedeterresautee** [comment]
I have not any exp with Javacpp, meaning I can PR a change of version but would have difficulties if it implies refactoring somewhere in the plugin...

**Comment by lloydmeta** [comment]
> I have not any exp with Javacpp, meaning I can PR a change of version but would have difficulties if it implies refactoring somewhere in the plugin...

No worries. I'll handle it :)
