### ISSUE TITLE
JavaCpp version not set correctly

### ISSUE THREAD

**Issue by vimalaguti** [bytedeco/sbt-javacpp#17]
Hi, I've noticed that it adds to dependencies the wrong version.

The patch version level of javacpp is removed (why this choice?).

The default as of now is javaCpp = 1.4
And if I add ffmpeg -> 3.4.1, it searches for version 3.4.1-1.4
So no one would notice any problem.

But I need the version javaCpp = 1.4.3
FFmpeg is now at version 4.0.2 but it searches for 4.0.2-1.4
Weird enough, it correctly download javacpp 1.4.3

https://github.com/bytedeco/sbt-javacpp/blob/31661b12400828bc61f4ec320e20eb78b42fde0f/src/main/scala/org/bytedeco/sbt/javacpp/Plugin.scala#L40

**Comment by lloydmeta** [comment]
> The patch version level of javacpp is removed (why this choice?).

When I made this plugin, the presets were only suffixed with $maj.$min from the JavaCPP version: see https://mvnrepository.com/artifact/org.bytedeco.javacpp-presets/ffmpeg

I'd like to hear more about this from @saudet on whether or not this has now changed or not before advancing with changing this.

<img width="975" alt="screenshot 2018-12-20 at 21 13 05" src="https://user-images.githubusercontent.com/914805/50284335-1b3e7c80-049c-11e9-8631-814e58700efc.png">

**Comment by saudet** [comment]
Yes, since we got CI up and running, we're making releases about every 3 months now, so they are not limited to minor releases of JavaCPP anymore:
http://bytedeco.org/news/2018/07/17/bytedeco-as-distribution/

**Comment by vimalaguti** [comment]
also keep in mind that I removed support for sbt 0.13 because I'm not sure on how to handle the cross build configuration.

**Comment by lloydmeta** [comment]
Just published 1.5; it should be on Maven Central in the next couple of hours; thanks again for your help :)
