### ISSUE TITLE
altering classpathTypes is the wrong solution

### ISSUE THREAD

**Issue by hvesalai** [bytedeco/sbt-javacpp#5]
While the classpathTypes hack does allow sbt to compile the JavaCPP dependent code, it will not produce a working .ivy file. The ivy file will have a default reference to the `javacpp` artifact and so it will not be included correctly in any downstream projects interpreting the ivy file.

The solution is to do 

```
libraryDependencies += "org.bytedeco" % "javacpp" % "1.2.2" jar
```

(i.e. no classpathTypes, but instead "jar" added to the end of the row)

This will cause both sbt and the ivy generated by it to have a correct reference to the jar of javacpp.

**Comment by lloydmeta** [comment]
Hi there,

Thanks for the heads up and the proposed solution. Can you try it out locally and send a PR ?

**Comment by hvesalai** [comment]
Hi, from the discussion in bytedeco/javacpp#113 I got the impression that the sub-optimal packaging of javacpp causing this whole problem is going to be changed so that the core of javacpp would be a normal jar and the maven-plugin would be a separate thing. If that would happen, then this and the classpathTypes hack would both be obsolete.
